apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-project-kubequest-backend-cert
  namespace: dev-project-kubequest-backend
spec:
  secretName: dev-project-kubequest-backend-tls
  dnsNames:
    - dev.kubequest.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
