apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-project-kubequest-backend-cert
  namespace: staging-project-kubequest-backend
spec:
  secretName: staging-project-kubequest-backend-tls
  dnsNames:
    - staging.kubequest.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
