apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-project-kubequest-backend-cert
  namespace: prod-project-kubequest-backend
spec:
  secretName: prod-project-kubequest-backend-tls
  dnsNames:
    - kubequest.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
