apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-project-kubequest-backend-deployment
  namespace: prod-project-kubequest-backend
  labels:
    app: prod-project-kubequest-backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Un nouveau pod en plus des existants max
      maxUnavailable: 0 # Aucun pod ne doit être indisponible pendant l'update (zero-downtime)
  progressDeadlineSeconds: 300 # Timeout max pour un déploiement (rollback si dépassé)
  revisionHistoryLimit: 5 # Garde les 5 dernières versions pour 
  affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution: # C’est une préférence, pas une obligation -> si ce n’est pas possible, le pod sera quand même programmé
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - prod-project-kubequest-backend
          topologyKey: kubernetes.io/hostname
  selector:
    matchLabels:
      app: prod-project-kubequest-backend
  template:
    metadata:
      labels:
        app: prod-project-kubequest-backend
    spec:
      containers:
        - name: prod-project-kubequest-backend
          image: corentin35/project-kubequest-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              value: '3333'
          resources:
            requests:
              cpu: '300m'
              memory: '400Mi'
            limits:
              cpu: '600m'
              memory: '800Mi'
      imagePullSecrets:
        - name: regcred
