apiVersion: v1
kind: Service
metadata:
  name: prod-project-kubequest-backend-service
  namespace: prod-project-kubequest-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: prod-project-kubequest-backend
